// Generated by Wrangler on Sat Sep 07 2024 20:41:03 GMT+0800 (China Standard Time)
// by running `wrangler types`

interface Env {
  ALLOWED_ORIGINS: 'https://sqybi.com';
  COMMENT_DB: D1Database;
}
